---
- hosts: 172.31.65.234
  become: yes
  tasks:
  - name: i wantto execute direct linux cmd
    command: hostname -f
    register: myfirsttaskresult

  - name: i want display the first task result
    debug:
      msg: "{{myfirsttaskresult}}"
  - name: install git
    apt: 
      name: git
      state: present
    when: myfirsttaskresult.stderr == ""

  - name: install tree
    apt: 
       name: tree
       state: present
    when: myfirsttaskresult.stderr != ""