---
- hosts: 172.31.65.234
  become: yes
  tasks:
  - name: install git
    apt: 
      name: git
      state: present
    tags: mygit

  - name: install tree
    apt: 
       name: tree
       statee: present
    tags: mytree  
    ignore_errors: yes

  - name: install wget
    apt:
       name: wget
       state: present
    tags: mywget